libapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^(?P<item_id>\d+)/$', views.detail, name='detail'),
        url(r'^suggestions/$', views.suggestions, name='suggestions'),
        url(r'^suggestionsdetails/(?P<item_id>\d+)$', views.suggestionsdetail, name='suggestionsdetail'),
        url(r'^searchlib/$', views.searchlib, name='searchitem'),
        url(r'^newitem/$', views.newitem, name='newitem'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^myitems/$', views.myitems, name='myitems'),
        url(r'^myitems/(?P<item_id>\d+)$', views.detail,name='myitemsdetails'),
        url(r'^register/$', views.register, name='register'),
        ]

libsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from libapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^libapp/', include('libapp.urls', namespace='libapp')),
    url(r'^libapp/about/', include('libapp.urls', namespace='about')),


]

libapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here.
class Libuser(User):
    PROVINCE_CHOICES = (
        ('AB','Alberta'),  # The first value is actually stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    # age = models.IntegerField()
    phone = models.IntegerField(null=True)
    postalcode = models.CharField(max_length=7, blank=True,null=True)
    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Libitem(models.Model):
    TYPE_CHOICES = (
        ('Book', 'Book'),
        ('DVD','DVD'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=100)
    itemtype = models.CharField(max_length=6, choices=TYPE_CHOICES, default='Book')
    checked_out=models.BooleanField(default=False)
    user=models.ForeignKey(Libuser, default=None, null=True, blank=True)
    duedate=models.DateField(default=None, null=True, blank=True)
    last_chkout = models.DateField(default=None, null=True, blank=True)
    date_acquired = models.DateField(default=datetime.date.today())
    pubyr = models.IntegerField()
    num_chkout = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title + ' by ' + self.itemtype

    def overdue(self):
        if self.checked_out == True:
            if self.duedate < datetime.date.today():
                return 'Yes'

class Book(Libitem):
    CATEGORY_CHOICES = (
        (1, 'Fiction'),
        (2, 'Biography'),
        (3, 'Self Help'),
        (4, 'Education'),
        (5, 'Children'),
        (6, 'Teen'),
        (7, 'Other'),
    )
    author = models.CharField(max_length=100)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)

    def __str__(self):
        return self.title + ' by ' + self.author


class Dvd(Libitem):
    CATEGORY_CHOICES = (
        (1, 'G'),
        (2, 'PG'),
        (3, 'PG-13'),
        (4, '14A'),
        (5, 'R'),
        (6, 'NR'),

    )
    maker = models.CharField(max_length=100)
    duration = models.IntegerField(help_text="In Minutes")
    rating = models.IntegerField(choices=CATEGORY_CHOICES,max_length=100)

    def __str__(self):
        return self.title + ' by ' + self.maker +' of duration ' + str(self.duration) + ' minutes and rating '+ str(self.rating)

class Suggestion(models.Model):

    TYPE_CHOICES = (
        (1, 'Book'),
        (2,'DVD'),
        (3, 'Other'),
    )
    title = models.CharField(max_length=100)
    pubyr = models.IntegerField(null=True, blank=True)
    type = models.IntegerField(default=1, choices=TYPE_CHOICES)
    cost = models.IntegerField()
    num_interested = models.IntegerField()
    comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title

libapp/forms.py
from django import forms
from libapp.models import Suggestion, Libuser

TYPE_CHOICES = (
    (1, 'Book'),
    (2, 'DVD'),
    (3, 'Other'),
)

class SuggestionForm(forms.ModelForm):
   class Meta:
        model = Suggestion
        exclude = ['num_interested']
        labels = {'cost':'Estimated Cost in Dollars'}

        title = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'max_length': 100}))
        pubyr = forms.IntegerField(widget=forms.NumberInput())
        type = forms.RadioSelect()
        cost = forms.IntegerField(widget=forms.NumberInput())
        comments = forms.CharField(widget=forms.Textarea())

class SearchlibForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter Title"}),label='',required=False)
    author = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter Author/Maker"}), label='',required=False)

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'required': True, 'class': 'validate', 'placeholder': 'Username'}), label="")
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'required': True, 'class': 'validate input-field', 'placeholder': 'Password'}),
        label="")
#
# class Register(forms.ModelForm):
#     class Meta:
#         model = Libuser
#         fields = ['username', 'password', 'password1', 'first_name', 'last_name', 'email', 'address', 'city', 'province',
#                   ]
#
#
#     password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'validate'}), label="Password")
#     password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'validate'}), label="Confirm Password")

class RegisterForm(forms.ModelForm):
    class Meta:
        model = Libuser
        fields = ['username', 'password', 'first_name', 'last_name', 'email']
        exclude = ['address', 'city', 'province']
    username = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'max_length': 200}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'required': True, 'max_length': 200}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'max_length': 200}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'max_length': 200}))
    email = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'max_length': 200}))

libapp/views.py
from random import randint

from django.contrib.auth.hashers import make_password
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
# Create your views here.
# Import necessary classes
from django.http import HttpResponse

from libapp.forms import SuggestionForm, SearchlibForm, RegisterForm, LoginForm
from libapp.models import Book, Dvd, Libuser, Libitem, Suggestion,Libuser
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test

import operator
# Create your viewsx     here.

def register(request):
    NEWUSER = Libuser.objects.all()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            NEWUSER = form.save(commit=False)
            NEWUSER.num_interested = 1
            NEWUSER.password = make_password(form.cleaned_data['password'])
            NEWUSER.save()
            return HttpResponseRedirect('/libapp/login/')
        else:
            return render(request, 'libapp/register.html', {'form': form})
    else:
        form = RegisterForm()
        return render(request, 'libapp/register.html', {'form': form})


def myitems(request):
    itemob = Libitem.objects.filter(user__username=request.user.username, checked_out=True)
    return render(request, 'libapp/myitems.html', {'itemob': itemob})

def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                luckynum = randint(0, 9)
                request.session['luckynum'] = luckynum
                request.session.set_expiry(3600)
                return HttpResponseRedirect('/libapp/')
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'libapp/login.html',{'form': form})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('libapp:index')))


def searchlib(request):
    if request.method == 'POST':
        SearchlibForm(request.POST)
        title1 = request.POST['title']
        author1 = request.POST['author']
        if title1 != '' and author1 != '':  # Title and User not null
            bookob = Book.objects.filter(title__contains=title1, author__contains=author1)
            dvdob = Dvd.objects.filter(title__contains=title1, maker__contains=author1)
            form = SearchlibForm()
            if bookob and dvdob:
                return render(request, 'libapp/searchitem.html', {'bookob': bookob, 'dvdob': dvdob, 'form': form})
            elif not bookob and dvdob:
                return render(request, 'libapp/searchitem.html', {'dvdob': dvdob, 'form': form})
            elif bookob and not dvdob:
                return render(request, 'libapp/searchitem.html', {'bookob': bookob, 'form': form})
            else:
                return render(request, 'libapp/searchitem.html', {'notfound': True, 'form': form})

        elif title1 != '' and author1 == '':  # Only Title searched
            bookob = Book.objects.filter(title__contains=title1)
            dvdob = Dvd.objects.filter(title__contains=title1)
            form = SearchlibForm()
            if bookob and dvdob:
                return render(request, 'libapp/searchitem.html', {'bookob': bookob, 'dvdob': dvdob, 'form': form})
            elif bookob and not dvdob:
                return render(request, 'libapp/searchitem.html', {'bookob': bookob, 'form': form})
            elif not bookob and dvdob:
                return render(request, 'libapp/searchitem.html', {'dvdob': dvdob, 'form': form})
            else:
                return render(request, 'libapp/searchitem.html', {'notfound': True, 'form': form})

        elif author1 != '' and title1 == '':  # Only Author searched
            bookob = Book.objects.filter(author__contains=author1)
            dvdob = Dvd.objects.filter(maker__contains=author1)
            form = SearchlibForm()
            if bookob and dvdob:
                return render(request, 'libapp/searchitem.html', {'bookob': bookob, 'dvdob': dvdob, 'form': form})
            elif bookob and not dvdob:
                return render(request, 'libapp/searchitem.html', {'bookob': bookob, 'form': form})
            elif not dvdob and bookob:
                return render(request, 'libapp/searchitem.html', {'dvdob': dvdob, 'form': form})
            else:
                form = SearchlibForm()
                return render(request, 'libapp/searchitem.html', {'notfound': True, 'form': form})

        else:  # Author and Title null
            form = SearchlibForm()
            return render(request, 'libapp/searchitem.html', {'notinput': True, 'form': form})

    else:
        form = SearchlibForm()
        return render(request, 'libapp/searchitem.html', {'form': form})


def newitem(request):
    suggestions = Suggestion.objects.all()
    if request.method == 'POST':
        form = SuggestionForm(request.POST)
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.num_interested = 1
            suggestion.save()
            return HttpResponseRedirect('/libapp/suggestions/')
        else:
            return render(request, 'libapp/newitem.html', {'form':form, 'suggestions':suggestions})
    else:
        form = SuggestionForm()
        return render(request, 'libapp/newitem.html', {'form':form, 'suggestions':suggestions})


def newitem1(request):
    return  render(request,'libapp/newitem.html')

def suggestions(request):
    suggestionlist = Suggestion.objects.all()[:10]
    return render(request, 'libapp/suggestions.html', {'itemlist':   suggestionlist})

def suggestionsdetail(request,item_id):
    item = Suggestion.objects.get(pk=item_id)
    return render(request, 'libapp/suggestionsdetails.html', {'item': item})

def detail(request,item_id):
    item = Libitem.objects.get(pk=item_id)
    if item.itemtype == 'Book':
        item = Book.objects.get(pk=item_id)
    else:
        item = Dvd.objects.get(pk=item_id)
    return render(request, 'libapp/detail.html', {'item': item})

def detail1(request, item_id):
    response = HttpResponse()
    type='Book'
    try:
        item = Book.objects.get(pk=item_id)
        para3 = '<p>Author: ' + str(item.author) + '</p>'
    except Book.DoesNotExist:  # catch the DoesNotExist error
        # item = Dvd.objects.get(pk=item_id)
        item = get_object_or_404(Dvd, pk=item_id)
        type = 'Dvd'
        para3 = '<p>Maker: ' + str(item.maker) + '</p>'

    para = '<p>This is a ' + type + '</p>'
    para1 = '<p>Title: ' + item.title + '</p>'
    para2 = '<p>Due Date: ' + str(item.duedate) + '</p>'
    response.write(para)
    response.write(para1)
    response.write(para2)
    response.write(para3)

    return response

def index(request):
    itemlist = Libitem.objects.all().order_by('title')[:10]
    return render(request, 'libapp/index.html', {'itemlist': itemlist})


def index1(request):
    booklist = Book.objects.all() [:10]
    response = HttpResponse()
    heading1 = '<p>' + 'List of books: ' + '</p>'
    response.write(heading1)
    for book in booklist:
        para = '<p>' + str(book) + '</p>'
        response.write(para)

    dvdlist = Dvd.objects.all().order_by('pubyr') [:5]
    heading2 = '<p>' + 'List of dvds: ' + '</p>'
    response.write(heading2)
    for dvd in dvdlist:
        para1 = '<p>' + str(dvd) + '</p>'
        response.write(para1)
    return response


def about(request):
    visits = int(request.COOKIES.get('about_visits',0))
    visits +=1
    response = render(request, 'libapp/about.html',{'visits':visits})
    response.set_cookie('about_visits',visits)
    return response

def about1(request):
    response =  HttpResponse()
    heading1 = '<p>' + 'This is a Library APP.' + '</p>'
    response.write(heading1)
    return response

libapp/templates/libapp/about.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <h2>
    This is Library App <br/><br/><br/>

    Congratulations!<br/><br/>
        you are the  {{ visits }} visitor of this page!<br/><br/>
    Thank you!
    </h2>
{% endblock %}

libapp/templates/libapp/about_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
This is Library App
{#<p><a href="/libapp/">Index page</a></p>#}
<p><a href="{% url 'libapp:index' %}">About page</a></p>
</body>
</html>

libapp/templates/libapp/base.html
{#<!DOCTYPE html>#}
{#{% load staticfiles %}#}
{##}
{#<html>#}
{#    <head>#}
{#        <link rel="stylesheet" type="text/css" href="{% static 'libapp/style.css' %}" />#}
{#        <title>MAC Library APP - {% block title %}Welcome!{% endblock %}</title>#}
{#    </head>#}
{##}
{#    <body>#}
{#        <div>#}
{#            {% if request.user.username %}#}
{#            <ul>#}
{#                <li><a href="{% url 'libapp:myitems' %}">My Items</a></li>#}
{#                <li><a href="{% url 'libapp:logout' %}">Logout</a></li>#}
{#            </ul>#}
{#            {% else %}#}
{#                <li><a href = "{% url 'libapp:login' %}">Login</a></li>#}
{#                <li><a href = "{% url 'libapp:register' %}">Register</a></li>#}
{#            {% endif %}#}
{#        </div>#}
{#        <div>#}
{##}
{#            <h1>{% block myhdg %}Hello {{ request.user.first_name }} {{ request.user.last_name }} {% endblock %}</h1>#}
{#        <hr />#}
{#        <hr />#}
{#            {% block body_block %}*** {% endblock %}#}
{##}
{#        </div>#}
{#        <hr />#}
{#        <hr />#}
{#        <div>#}
{#            <ul>#}
{#                <br>#}
{#                <li class="hbar1"><a href="/libapp/about/"> About this site</a></li>#}
{#                <br>#}
{#                <br>#}
{#                <br>#}
{#                <li class="hbar1"><a href = "{% url 'libapp:index' %}">Return to main page</a></li>#}
{#                <br>#}
{#                <br>#}
{#                <br>#}
{#                <li class="hbar1"><a href="/libapp/suggestions/">Suggestions</a></li>#}
{#                <br>#}
{#                <br>#}
{#                <br>#}
{#                <li class="hbar1"><a href="/libapp/searchlib/">Searchitems</a></li>#}
{#                <br>#}
{#                <br>#}
{#                <br>#}
{#                <li class="hbar1"><a href="/libapp/newitem/">Newitems</a></li>#}
{#                <br>#}
{#                <br>#}
{#                <br>#}
{#            </ul>#}
{#        </div>#}
{#    </body>#}
{#</html>#}
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'libapp/css/foundation.css' %}" />
        <title>MAC Library APP - {% block title %}Welcome!{% endblock %}</title>
    </head>

    <body>
            <div class="top-bar">
            <div class="top-bar-left">
            <ul class="menu">
                <li><a href="/libapp/about/"><strong>About this site</strong></a></li>
                <li><a href = "{% url 'libapp:index' %}">Return to main page</a></li>
                <li><a href="/libapp/suggestions/">Suggestions</a></li>
                <li><a href="/libapp/searchlib/">Searchitems</a></li>
                <li><a href="/libapp/newitem/">Newitems</a></li>
            </ul>
             </div>
                <div class="top-bar-right">
                    {% if request.user.username %}
        <ul class="menu">
                <li><a href="{% url 'libapp:myitems' %}">My Items</a></li>
                <li><a class="button" href="{% url 'libapp:logout' %}">Logout</a></li>
        </ul>
                    {% else %}
                        <ul class="menu">
                     <li><a class="button" href = "{% url 'libapp:login' %}">Login</a></li>
                <li><a href = "{% url 'libapp:register' %}">Register</a></li>
                          </ul>
            {% endif %}
        </div>
        </div>
            <div class="row">
        <div id="wrapper">
        <div class="column row">
            <img style="height:200px;width:1260px;" src="{% static 'libapp/img/night.jpeg' %}">

            <h4 class="subheader">{% block myhdg %}Hello {{ request.user.first_name }} {{ request.user.last_name }} {% endblock %}</h4>

                <hr />
        <hr />
            {% block body_block %}*** {% endblock %}
        </div>
        </div>
        <hr />
        <hr />

</div>

    <script>
    $(document).foundation();
    </script>
    <script src="{% static 'libapp/js/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'libapp/js/vendor/what-input.min.js'%}"></script>
    <script src="{% static 'libapp/js/foundation.min.js'%}"></script>
    </body>

</html>

libapp/templates/libapp/detail.html
{% extends 'libapp/base.html' %}
{% block body_block %}
 {% if item.itemtype == 'Book' %}
        <h2>Detail of Book items</h2>

        Title : {{ item.title }}<br>
        Publication year:{{ item.pubyr }}<br>
        Author:{{ item.author }}<br>
        Category:  {{ item.category }}<br>



    {% else %}
    <h2>Detail of Dvd items</h2>
         Title   :{{ item.title }}<br>
         Publication year: {{ item.pubyr }} <br>
         Maker   :{{ item.maker }}<br>
         Duration   :  {{ item.duration }}<br>
         Rating   :{{ item.rating }}<br>

    {% endif %}
{% endblock %}

libapp/templates/libapp/detail_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>

{% if item.itemtype == 'Book' %}
        <h2>Detail of Book items</h2>

        Title : {{ item.title }}<br>
        Publication year:{{ item.pubyr }}<br>
        Author:{{ item.author }}<br>
        Category:  {{ item.category }}<br>



    {% else %}
    <h2>Detail of Dvd items</h2>
         Title   :{{ item.title }}<br>
         Publication year: {{ item.pubyr }} <br>
         Maker   :{{ item.maker }}<br>
         Duration   :  {{ item.duration }}<br>
         Rating   :{{ item.rating }}<br>

    {% endif %}
<p><a href="{% url 'libapp:index' %}">Index page</a></p>

</body>
</html>

libapp/templates/libapp/index.html
{#{% extends 'libapp/base.html' %}#}
{##}
{#{% block body_block %}#}
{#    {% if itemlist %}#}
{#        <h2>List of Library items</h2>#}
{#        <ol>#}
{#            {% for item in itemlist %}#}
{#                <li><a href="/libapp/{{ item.id }}" >{{ item.itemtype }}:  {{ item}}</a> </li>#}
{#            {% endfor %}#}
{#        </ol>#}
{##}
{#    {% else %}#}
{#        <strong>There are no available items!</strong>#}
{#    {% endif %}#}
{#    {% if luckynum  %}#}
{#        <p>Your lucky number is: {{ request.session.luckynum }}</p>#}
{#        {% else %}#}
{#        <p>Your lucky number is: 0</p>#}
{#    {% endif %}#}
{#{% endblock %}#}
{% extends 'libapp/base.html' %}

{% block body_block %}

    <div class="large-8 large-centered columns">
    {% if itemlist %}
        <h4 class="subheader">List of Library items</h4>
        <ol>
            {% for item in itemlist %}
                <div class="row medium-8 large-7 columns">
                <div class="blog-post">

                <li><a href="/libapp/{{ item.id }}" ><span class="success badge">{{ item.itemtype }}</span>:  {{ item}}</a>
                </div>
                </div>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}
    <div class="warning callout" style="width:30%">
    {% if luckynum  %}

        <p>Your lucky number is: {{ request.session.luckynum }}</p>
        {% else %}
        <p>Your lucky number is: 0</p>

    {% endif %}
    </div>
    </div>


{% endblock %}

libapp/templates/libapp/index_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>My Library APP</title>
</head>

<body>
    {% if itemlist %}
        <h2>List of Library items</h2>
        <ol>
            {% for item in itemlist %}
                <li><a href="/libapp/{{ item.id }}" >{{ item.itemtype }}:  {{ item}}</a> </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}
{#<p><a href="/libapp/about">About page</a></p>#}
<p><a href="{% url 'libapp:about' %}">About page</a></p>
</body>
</html>

libapp/templates/libapp/login.html
{% extends 'libapp/base.html' %}

{% block body_block %}
{#    <form method="post" action="/libapp/login/">{% csrf_token %}#}
{#    <input type="text" placeholder="Username" name="username"><br>#}
{#    <input type="text" placeholder="Password" name="password"><br>#}
{#    <input type="submit" value="submit">#}
{#    </form>#}
    <form action="." method="post" class="form-row" style="width:30%">{% csrf_token %}
        {{ form.as_p }}<br/>
        <button type="submit" class="button" value="LogIN">Login</button><br/>

        </form>
{% endblock %}


libapp/templates/libapp/myitems.html
{% extends 'libapp/base.html' %}
{% block body_block %}
{% if itemob and request.user.username %}
    <h2>Checked out items</h2><br/>
    <ol>
    {% for item in itemob %}
        <li><a href="/libapp/myitems/{{ item.id }}"> {{ item.title }}</a></li>
    {% endfor %}
    </ol>
    {% elif not itemob and request.user.username %}
         <h3>You do not have any checked out item</h3>
    {% else %}
    <h3>You need to Login to access this page</h3>
{% endif %}

{% endblock %}

libapp/templates/libapp/newitem.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div style="width: 45%; padding-left:100px;">
    <form class="form-row" method="post" action=".">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button" value="Submit">
        </form>
    </div>
{% endblock %}

libapp/templates/libapp/register.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div align="center">
<div style="width: 25%; align-items: center; padding-top: 3%" align="center">
    <div class="col s12 z-depth-5 card-panel">
        <h4>Registration Form!</h4><br/><br/>
        <div style="width: 75%">
            <form action="." method="post">{% csrf_token %}{{ form.as_p }}<br/>
            <br><input type="submit" value="Submit" class="btnpink col s12"/>
        </form>
            </div>
    </div>
    </div>
</div>
{% endblock %}

{#{% extends 'libapp/base.html' %}#}
{#{% block body_block %}#}
{#    <div align="center">#}
{#<div style="width: 45%; align-items: center; padding-top: 3%" align="center">#}
{#    <div class="row">#}
{#        <h4>Registration Form!</h4><br/><br/>#}
{#        <div style="width: 75%">#}
{#            <form class="form-row" action="." method="post">{% csrf_token %}{{ form.as_p }}<br/>#}
{#            <br><input type="submit" value="Submit" class="button"/>#}
{#        </form>#}
{#            </div>#}
{#    </div>#}
{#    </div>#}
{#</div>#}
{#{% endblock %}#}

libapp/templates/libapp/searchitem.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div style="width: 18%">
    {% if notfound == True %}
        <ul>
        <li><p style="font-size: small">Book not found</p></li>
        </ul>
    {% endif %}
    {% if notinput %}
       <ul>
        <li><p style="font-size: small">No input provided for search.</p></li>
        </ul>
    {% endif %}

    <form action="." method="post">{% csrf_token %}
        {{ form.as_p }}<br/>
        <input type="submit" class="button" value="Submit"><br/>
    </form>
      </div>
    <h3>Search Results:</h3>
        {% if bookob and dvdob%}
            Total {{ bookob.count|add:dvdob.count }} results. <br/><br/>
                Search returned: {{ bookob.count }} books.<br/>
                <ol>
                {% for book in bookob %}
                    <li><a href="{% url 'libapp:index' %}{{ book.id }}" style="text-decoration: underline; font-size: 130%"><cite>{{ book.title }}</cite></a><br/></li>
                {% endfor %}
                </ol>
                Search returned: {{ dvdob.count }} dvds.<br/>
                <ol>
                {% for dvd in dvdob %}
                    <li><a href="{% url 'libapp:index' %}{{ dvd.id }}" style="text-decoration: underline; font-size: 130%"><cite>{{ dvd.title }}</cite></a><br/></li>
                {% endfor %}
                </ol>

        {% elif bookob and not dvdob%}
            Search returned: {{ bookob.count }} books.<br/>
            <ol>
            {% for book in bookob %}
                <li><a href="{% url 'libapp:index' %}{{ book.id }}" style="text-decoration: underline; font-size: 130%"><cite>{{ book.title }}</cite></a><br/></li>
            {% endfor %}
            </ol>
            {% elif not bookob and dvdob %}
            Search returned: {{ dvdob.count }} DVDs.<br/>
            <ol>
            {% for dvd in dvdob %}
                <li><a href="{% url 'libapp:index' %}{{ dvd.id }}" style="text-decoration: underline; font-size: 130%"><cite>{{ dvd.title }}</cite></a><br/></li>
            {% endfor %}
            </ol>
        {% else %}
            <p style="font-size: 130%">No results to display</p>
        {% endif %}

{% endblock %}

libapp/templates/libapp/suggestions.html
{% extends 'libapp/base.html' %}
{% block body_block %}
<div class="primary callout" style="width:35%;">
     <ol>
        {% for slist in itemlist %}
            <li><a href="/libapp/suggestionsdetails/{{ slist.id }}" >{{ slist.title }}</a> </li>
        {% endfor %}
     </ol>
</div>




{% endblock %}



libapp/templates/libapp/suggestionsdetails.html
{% extends 'libapp/base.html' %}
{% block body_block %}

<h2>Detail of Suggestion Item</h2>
<div class="primary callout" style="width:35%;">
Title : {{ item.title }}<br>
Publication year:{{ item.pubyr }}<br>
Type:{{ item.type }}<br>
Cost:  {{ item.cost }}<br>
Num_interested:{{ item.num_interested }}<br>
Comments:  {{ item.comments }}<br>
</div>

{% endblock %}